### ISSUE TITLE
Please support Deep Mob Learning - Blood Magic Addon

### ISSUE THREAD

**Issue by ghost** [floppaxd/DeepMobEvolution#10]
How about Deep Mob Evolution - Blood Magic Addon 👍

**Comment by Krutoy242** [comment]
Yes, +1 for this.
Want to add this mod to [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended), but need `DML-BM` support.

Crash when i tried to use your fork
[debug.log](https://github.com/ThePansmith/DeepMobEvolution/files/10302846/debug.log)

**Comment by GlodBlock** [comment]
there is the bm addon for dme https://www.curseforge.com/minecraft/mc-mods/deep-blood-evolution

**Comment by Krutoy242** [comment]
1 download? 😁
Ok, im gonna try it

**Comment by ghost** [comment]
yes.I will use it in my pack too.
