### ISSUE TITLE
Changing sprint key binding cause tooltip error (and also crash)

### ISSUE THREAD

**Issue by ASUT0R0** [floppaxd/DeepMobEvolution#14]
Data models won't show their tooltip if changed sprint key binding from shift to mouse button.
and hovering over them in inventory(not in JEI) will crash the game.

here's how the bug occurs.

https://imgur.com/gallery/CSLXrYN

**Comment by MobiliLavander** [comment]
> Data models won't show their tooltip if changed sprint key binding from shift to mouse button. and hovering over them in inventory(not in JEI) will crash the game.
> 
> here's how the bug occurs.
> 
> https://imgur.com/gallery/CSLXrYN

Hi, this also happens to me. When crafting an item it crashes my game.
