### ISSUE TITLE
Incorrect behaviour happens when using AE2 import bus to the simulation chamber.

### ISSUE THREAD

**Issue by YiRanMushroom** [floppaxd/DeepMobEvolution#15]
when using a storage bus to the drawer controller, inport bus cannot function correctly to the simulation chamber.
This is a very strange bug since it happens in a very specific condition. I am using PAE2 to build a subnet which is used to transport items from Deep Mob Evolution simulation chamber, and I found AE2 import bus cannot import items from the simulation chamber to the drawer controller, which is connected by a storage bus.

WHILE:
1.if ME system connects to another container it can import successfully.
2.Other conduits can export things from the chamber.
3.Import bus can import things from other containers to the drawer controller.

So I don't know the reason, maybe its a bug of PAE2, I would also post this issue there.

**Comment by serenibyss** [comment]
Could not reproduce on updated version of AE2
