### ISSUE TITLE
[Suggestion] Keep the simchamber in idle state with not enough energy for 1 simulation

### ISSUE THREAD

**Issue by disappeaTed** [floppaxd/DeepMobEvolution#31]
DML kept the simulation chambers in "idle" state if it has less than enough energy for a single simulation (cost*time), but DME starts a simulation with way less energy available and basically wastes the energy if not provided enough, aeügh.

**Comment by Exaxxion** [comment]
Some added context:

DML determines whether there is sufficient energy to begin a simulation by checking whether the internal buffer contains more than the product of the per-tick RF cost and the number of ticks in a simulation.
See: https://github.com/xt9/DeepMobLearning/blob/49dd143c02ae1c3cde0beca0609d5d5a90366c95/src/main/java/xt9/deepmoblearning/common/tiles/TileEntitySimulationChamber.java#L170-L177

DME determines whether there is sufficient energy by instead checking whether the internal buffer contains at least the per-tick RF cost.
See: https://github.com/floppaxd/DeepMobEvolution/blob/bf4702344d20a6b34cbb8be4c8129ff7184d8d38/src/main/java/mustapelto/deepmoblearning/common/tiles/TileEntityMachine.java#L123-L125
